name: Run Notion to Markdown Exporter

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:    

permissions:
  contents: write    

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Notion to Markdown script
        run: python notion_to_md.py

      - name: Commit and push generated files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add posts/*.md
          git commit -m "🤖 Auto-exported markdown files [skip ci]" || echo "Nothing to commit."
          git push
